### ISSUE TITLE
Cannot resolve keyword 'myapp_mymodel.lat' into field. Choices are: _ed_distance, lat, lng

### ISSUE THREAD

**Issue by psworld** [jneight/django-earthdistance#11]
I installed django-earthdistance as mentioned in the docs. But its still not working showing error.

my models are as following:
```python
class MyModel(models.Model):
    title = models.CharField(max_length=100)
    lat = models.FloatField()
    lng = models.FloatField()

    objects = EarthDistanceQuerySet.as_manager()
```
when I query the following in console:
`MyModel.objects.in_distance(100, fields=['lat', 'lng'], points=[lat, lng])`

I get the following errors:
`Cannot resolve keyword 'myapp_mymodel.lat' into field. Choices are: _ed_distance, lat, lng, title`

At the top it also gives a value error:
`ValueError: could not convert string to float: 'myapp_mymodel.lat'`

why these errors are showing up. How to fix it.

**Comment by blocher** [comment]
I'm also trying to work through this same issue which arose after upgrading from Django 1.11 to 2.2

**Comment by devinvenable** [comment]
Same issue here

**Comment by devinvenable** [comment]
This works for me.  It seems the logic in exception case is for joins, but the same logic is called even if the attribute is on the single model.  Not quite sure what changed that makes previously valid code no longer work, but I found that checking query.model to see if the attribute exists on the base model, and if it does, if I don't pre-pend the alias name, the code compiles and works.


diff --git a/django_earthdistance/models.py b/django_earthdistance/models.py
index a329ced..59856f7 100644
--- a/django_earthdistance/models.py
+++ b/django_earthdistance/models.py
@@ -30,7 +30,10 @@ class LlToEarth(models.Expression):
                 _, source, _, join_list, last = query.setup_joins(
                         six.text_type(p).split('__'), query.model._meta, query.get_initial_alias())[:5]
                 target, alias, _ = query.trim_joins(source, join_list, last)
-                final_points.append("%s.%s" % (alias, target[0].get_attname_column()[1]))
+                if hasattr(query.model, p):
+                    final_points.append("%s" % target[0].get_attname_column()[1])
+                else: 
+                    final_points.append("%s.%s" % (alias, target[0].get_attname_column()[1]))
             else:
                 final_points.append(six.text_type(p))
             c.params = final_points

**Comment by jneight** [comment]
Hi, @devinvenable I have applied your changes and tested it with versions up to 3.2 and it seems to be working fine. thanks!
