### ISSUE TITLE
'LlToEarth' object is not iterable error on Django 1.9

### ISSUE THREAD

**Issue by khlumzeemee** [jneight/django-earthdistance#4]
Hi
I'm getting the below error when calling the LlToEarth method on Django 1.9 and Python 3.5:
```
TypeError: 'LlToEarth' object is not iterable
```
I'm just running the code from the readme file but it wouldn't run.
P.S: I know you specified that it has been tested with Python 3.3 but I figured out sooner or later it would need to support the later versions as well.

**Comment by jneight** [comment]
Hi
Maybe something changed with django 1.9, I haven't tested it yet, I will check.

Can you copy the query here?

**Comment by khlumzeemee** [comment]
Hi
It's exactly the same query as in the read the docs page.

**Comment by jneight** [comment]
I saw the problem, it is just an error in the docs page. EarthDistance() should receive an iterable:

`MyModel.objects.filter(....).annotate(
    distance=EarthDistance([
        LlToEarth([0.2546, -38.25]),
        LlToEarth(['latitude', 'longitude'])
]))`
