### ISSUE TITLE
cannot import name EarthDistanceQuerySet

### ISSUE THREAD

**Issue by Gurubol** [jneight/django-earthdistance#5]
I am using version 0.6. Can you please let me know if I am missing anything?

**Comment by jneight** [comment]
EarthDistanceQuerySet is available in version 1.0, this version is for for django >= 1.8, if you are using django 1.7 and version 0.6, check the other branch https://github.com/jneight/django-earthdistance/tree/django17

**Comment by Gurubol** [comment]
@jneight, I thought the latest version was 0.6 till couple of days back. I can see 1 as the latest version. Thanks for your response.
