### ISSUE TITLE
Manager class ManagerFromEarthDistanceQuerySet not found

### ISSUE THREAD

**Issue by Gurubol** [jneight/django-earthdistance#6]
I have an existing manager class for my model and I want to use the manager from EarthDistanceQuerySet. Let us say my class is MyManager. 

So, I have following code:

class MyModel(models.Model):
    ...
    objects = MyManager()

When I do,

class MyManager(EarthDistanceQuerySet.as_manager()):
   ....

gives me following error:
"TypeError: Error when calling the metaclass bases
    __init__() takes exactly 1 argument (4 given)"

When I do:
from django.db.models.manager import ManagerFromEarthDistanceQuerySet
class MyManager(ManagerFromEarthDistanceQuerySet):
   ....

gives "cannot import name ManagerFromEarthDistanceQuerySet" error. Am I missing something? I don't have place to ask this question and hence logging an issue.

**Comment by jneight** [comment]
You are declaring the manager wrong:

if you just want to use EarthDistanceQuerySet as manager, just do

```python
from django_earthdistance.models import EarthDistanceQuerySet

class MyModel(models.Model)
   ...
   objects = EarthDistanceQuerySet.as_manager()
```

or if you want to use the EarthDistanceQuerySet and a custom manager, try with

```python
from django_earthdistance.models import EarthDistanceQuerySet

class MyManager(models.Manager):
    ... your custom methods here ...

class MyModel(models.Model)
   ...
   objects = MyManager.from_queryset(EarthDistanceQuerySet)()
```

more info: https://github.com/jneight/django-earthdistance/tree/django17

**Comment by Gurubol** [comment]
Thank you @jneight . This helped. If this is added in the documentation, it might help others too.
