### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [jneight/django-earthdistance#7]
How to make this results of `in_distance` method, sorted by distance. Like nearest first.

**Comment by SuperMasterBlasterLaser** [comment]
I have found the answer I neede to do something like this:

    models = MyModel.objects.in_distance(500, fields=['latitude', 'longitude'], points=[lat, lon]).order_by('_ed_distance')

**Comment by SuperMasterBlasterLaser** [comment]
Please add this in your documentation

**Comment by jneight** [comment]
I will add it, distance is annotated to the query so you can use it like any other attribute generated by django's annotate().

Also you can use parameter __annotate='name_to_use'__ when using in_distance() in case you want another name different of '_ed_distance'
